apiVersion: v1
kind: ReplicationController
metadata:
  name: my-calc-rc
spec:
  replicas: 2
  selector:
    app: my-calc
  template:
    metadata:
      labels:
         app: my-calc
    spec:
      containers:
      - name: my-calc
        image: daocloud.io/4admin2root/daocloud:master-3d6e625
---
apiVersion: v1
kind: Service
metadata:
  name: my-calc-service
spec:
  ports:
    - protocol: TCP
      port: 5000
  type: ClusterIP
  selector:
     app: my-calc
