apiVersion: v1
kind: ReplicationController
metadata:
  name: my-frontend-rc
spec:
  replicas: 2
  selector:
    app: my-frontend
  template:
    metadata:
      labels:
        app: my-frontend
    spec:
      containers:
      - name: my-frontend
        image: daocloud.io/4admin2root/daocloud:master-d21ed93
---
apiVersion: v1
kind: Service
metadata:
  name: my-frontend-service
spec:
  ports:
   - protocol: TCP
     port: 5000
     nodePort: 30080
  type: NodePort
  selector:
        app: my-frontend
