apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: slow
provisioner: kubernetes.io/glusterfs
parameters:
    resturl: "http://10.9.5.97:8080"
    clusterid: "41de078f9f62d17ac67d3cd7a4bb04d5"
    restuser: "admin"
    secretNamespace: "default"
    secretName: "heketi-secret"
    gidMin: "40000"
    gidMax: "50000"
    volumetype: "replicate:2"
---
apiVersion: v1
kind: Secret
metadata:
  name: heketi-secret
  namespace: default
data:
  # base64 encoded password. E.g.: echo -n "mypassword" | base64
     key: TXkgU2VjcmV0Cg==
type: kubernetes.io/glusterfs
