---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-jenkins-ingress
spec:
  rules:
  - host: ci-k.xzxpay.com
    http:
      paths:
      - path: /
        backend:
          serviceName: my-jenkins-jenkins
          servicePort: 8080
